filtered and sorted exam dates
neuland-ingolstadt/neuland.app pull request #117
Opened 2022-02-19 15:14 UTC by Curryking31

I filtered the examList to only show the real exams.
Also the exam dates are now sorted chronically.

2022-02-20 12:28 UTC, alexhorn requested changes

2022-02-20 12:28 UTC, alexhorn commented on rogue-thi-app/pages/calendar.js
> +  console.log(tempList)
Can you remove the logging statements? :)

2022-02-20 12:28 UTC, alexhorn commented on rogue-thi-app/pages/calendar.js
> +  tempList = tempList.filter((x) => x.modus !== '2')
What exactly does modus 2 mean? Might users be interested in seeing these?

2022-02-20 17:33 UTC, Curryking31 commented
Added a second commit with comments and without logs 👍

2022-02-21 09:53 UTC, M4GNV5 commented on rogue-thi-app/pages/calendar.js
> +  let tempList = examList
as `filter` returns a new list and `sort` returns the list itself too we do not really need a mutable variable here. A common thing to do is to simply chain the calls as in `return examList.map(...).filter(...).sort(...)`

I guess i can implement that in a new commit. Thanks for the PR :smiley:

2022-02-21 09:54 UTC, merged