Fix the text overflow in the mobility card in retro themes
neuland-ingolstadt/neuland.app pull request #178
Opened 2023-02-02 16:58 UTC by OverloaderV

This removes the programmatic truncating of the strings and instead uses css rules to just show "..." if the string is to long. This should work with any string and any theme
I'm only aware of the overflow happening in the mobility card but if it happens anywhere else, these css rules should be applicable

This fixes #177

2023-02-02 19:02 UTC, alexhorn requested changes
Unfortunately this appears to break the default theme:
![image](https://user-images.githubusercontent.com/13948008/216424765-c0f2c5ac-5b85-42dc-915a-e07fd233c4f5.png)

2023-02-02 23:19 UTC, OverloaderV commented
It should now work fine, the default layout looks like this now
![image](https://user-images.githubusercontent.com/22007229/216472636-50e15701-ae4e-4d89-aa02-3c063f4672b3.png)

However in retro theme long words previously cause the departure time to be displayed in a new line
![image](https://user-images.githubusercontent.com/22007229/216472739-02b96805-a6ac-49ea-b971-4befbb32d181.png)

Now it's in the same line, truncating the string earlier
![image](https://user-images.githubusercontent.com/22007229/216472870-d16de72a-b96c-465b-addc-e75b77f50d91.png)

In my opinion this looks better too, but it's not the previous behavior. If thats wanted I'll probablyhave to programmatically add another class iif the retro theme is selected

2023-02-03 09:12 UTC, OverloaderV commented
Converted to draft as I found another case of overflow that needs to be fixed preferably by a line break. See the newest comment in #177

2023-02-04 13:28 UTC, alexhorn approved these changes

2023-02-04 13:29 UTC, merged