Implement mock API server
neuland-ingolstadt/neuland.app pull request #296
Opened 2023-06-30 20:32 UTC by alexhorn

A mock server is needed to enable newcomers to develop without having to request an API key

2023-06-30 21:51 UTC, alexhorn commented
https://mock.neuland.app/

2023-07-04 21:12 UTC, M4GNV5 requested changes

2023-07-04 21:12 UTC, M4GNV5 commented on mock-server/app.js
> +const services = {
There are a lot of services missing

2023-07-04 21:12 UTC, M4GNV5 commented on mock-server/app.js
> +        isalive: params => ({
maybe we should put some minimal effort into these mock API requests (such as session&parameter checking).
This makes the mock server more useful for unit testing

2023-07-04 21:12 UTC, M4GNV5 commented on mock-server/app.js
> +            res.json(services[service][method](req.body))
We should probably wrap the service call into a try catch and mock the error status behaviour the official API responds with

2023-10-09 11:28 UTC, closed without merging