Room availability
neuland-ingolstadt/neuland.app pull request #354
Opened 2023-10-29 20:13 UTC by pl0ss

https://github.com/neuland-ingolstadt/neuland.app/issues/142

2023-10-29 21:47 UTC, BuildmodeOne requested changes
![image](https://github.com/neuland-ingolstadt/neuland.app/assets/39560569/6db2a14c-88fe-4358-921c-653440523f13)

Time of testing: 29.10.2023 - 22:46

2023-10-29 21:54 UTC, BuildmodeOne requested changes

2023-10-29 21:54 UTC, BuildmodeOne commented on rogue-thi-app/components/RoomMap.jsx
> +  // useEffect(() => {
please remove the comments :)

2023-10-29 21:54 UTC, BuildmodeOne commented on rogue-thi-app/components/RoomMap.jsx
> +              {/* {t('rooms.map.freeFromUntil', {
here as well

2023-10-29 21:54 UTC, BuildmodeOne commented on rogue-thi-app/components/RoomMap.jsx
> +
and here

2023-10-29 21:54 UTC, BuildmodeOne commented on rogue-thi-app/lib/backend-utils/rooms-utils.js
> +  const devmode = false //!
Good for testing purposes but shouldn't be in the project.

2023-10-29 21:54 UTC, BuildmodeOne commented on rogue-thi-app/lib/backend-utils/rooms-utils.js
> +    // Zeiten verbinden //? nochmal verbinden? Kann ich nicht testen, da es immer so pausen dazwischen gibt
Please keep the comments in English.

2023-10-29 21:54 UTC, BuildmodeOne commented on rogue-thi-app/lib/backend-utils/rooms-utils.js
> +  // console.log(roomList)
please remove all debug `console.log` calls :)

2023-10-29 21:54 UTC, BuildmodeOne commented on rogue-thi-app/components/RoomMap.jsx
> +        let fromDate
Not biggest fan of `let` but this is just my taste.

2023-10-30 20:09 UTC, pl0ss commented
<img width="392" alt="Bildschirmfoto 2023-10-30 um 20 38 18" src="https://github.com/neuland-ingolstadt/neuland.app/assets/65730791/8ac9eb35-2089-45c3-8c90-4a77904059cd">

This is how it would look on October 30th at 12 o'clock


<img width="376" alt="Bildschirmfoto 2023-10-30 um 20 44 43" src="https://github.com/neuland-ingolstadt/neuland.app/assets/65730791/fd4fd8c7-ef66-40bc-b7f8-0fcd3eb044a5">

and at 20 o'clock

2023-10-31 15:58 UTC, Robert27 commented on rogue-thi-app/components/RoomMap.jsx
> +                checked={i === filteredFloorOrder.length - (searchText ? 1 : 2)}
When searching for `I` this shows the basement by default. 
However basements are not that relevant, which is why we should still display the ground floor.

2023-10-31 22:21 UTC, Robert27 approved these changes

2023-10-31 22:36 UTC, BuildmodeOne approved these changes

2023-10-31 22:39 UTC, Robert27 approved these changes

2023-10-31 22:40 UTC, merged